spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: cao19981128
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    host: localhost
    password:
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 100





mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰规则
my:
  name: 11
server:
  port: 1314